# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PicturesDataset": "autoencoder.ipynb",
         "plot_pictures": "autoencoder.ipynb",
         "autoencoder_": "autoencoder.ipynb"}

modules = ["autoencoder.py"]

doc_url = "https://alejandroxag.github.io/super_resolution/"

git_url = "https://github.com/alejandroxag/super_resolution/tree/master/"

def custom_doc_links(name): return None
